<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><?php echo App::config("nazivApp") ?></title>
<link rel="stylesheet" href="<?php echo App::config("url") ?>public/css/foundation.css">
<!-- <link href="https://fonts.googleapis.com/css?family=Roboto&amp;subset=latin-ext" rel="stylesheet"> -->
<!-- https://www.fontsquirrel.com/tools/webfont-generator -->
<!-- svoj font uploadati i pratiti tutorial -->
<link rel="stylesheet" href="<?php echo App::config("url") ?>public/css/app.css">
<script defer src="https://use.fontawesome.com/releases/v5.6.3/js/all.js" integrity="sha384-EIHISlAOj4zgYieurP0SdoiBYfGJKkgWedPHH4jCzpCXLmzVsw1ouK59MuUtP4a1" crossorigin="anonymous"></script>
<!-- https://favicon.io/favicon-generator/ -->
<link rel="shortcut icon" href="<?php echo App::config("url")?>public/apple-touch-icon" sizes="180x180" href="shortcut icon" href="<?php echo App::config("url")?>public/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="shortcut icon" href="<?php echo App::config("url")?>/public/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="<?php echo App::config("url")?>/public/favicon-16x16.png">
<link rel="manifest" href="<?php echo App::config("url")?>/public/site.webmanifest">
