<div class="grid-x">
  <div class="cell large-6"><img src="<?php 
   
   $putanja = App::config("url") . "public/img/intro.gif"; 
    echo $putanja ?>" alt="" width="700" height="900"  />
</div>

   <div class="cell large-6">
   
   
   <p> <h4 class="text-center"> Kreirajte i uređujte vlastito natjecanje </h4> <p>
   <br/>
   <p class="text-center"> U samo par jednostavnih koraka kreirajte vlastito nogometno,rukometno,esport ili neko drugo natjecanje:</p>
   <br/>
   <p>
    <ol class="text-center">
        <li class="text-center">Kreirajte ligu, na izboru vam je jednokruzno ili dvokružno natjecanje</li>
        <li class="text-center">Dodajte natjecatelje</li>
        <li class="text-center">Unesite rezultate</li>
    </ol>
 
    </p>
   <br>
   <p class="text-center"> Raspored igranja,poredak,rezultate, top strijelce (opcionalan unos) aplikacija za vas generira automatski. </p>
   
   
   
   
   
   
   
   
   </div>
</div>

