<div class="grid-x">
    <div class="large-12 medium-12 small-12 columns">
        <div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
            <button class="menu-icon" type="button" data-toggle="example-menu"></button>
            <div class="title-bar-title">Izbornik</div>
            </div>

            <div class="top-bar" id="example-menu">
            <div class="top-bar-left">
                <ul class="dropdown menu" data-dropdown-menu>
                
                <li>
                <a href="<?php echo App::config("url")."index" ?>"><i class="fas fa-home"></i> Početna</a>
                </li>
                <li>
                <a href="<?php echo App::config("url")."onama" ?>"><i class="fas fa-user"></i> O nama</a>
                </li>
                <li>
                <a href="<?php echo App::config("url")."kontakt" ?>"> <i class="fas fa-address-card"></i> Kontakt</a>
                </li>
                </ul>
            </div>
            <div class="top-bar-right">
                <ul class="menu" id="top-right">
                <?php if(Session::getInstance()->isLogiran()):?>
                <a href="<?php echo App::config("url") ?>admin/odjava">Odjava 
                <?php echo Session::getInstance()->getUser()->firstNamelastName?></a>
                <?php else:?><a href="<?php echo App::config("url") ?>admin/prijava">Prijava</a>
                <?php endif;?>

                </ul>
            </div>
        </div>
    </div>
</div>