<!doctype html>
<html class="no-js" lang="en" dir="ltr">

<head>
    <?php include_once "head.phtml"?>
</head>

<body>
    <div class="grid-container">

        <div class="grid-x">
            <!-- <div class="large-2 medium-2 columns hide-for-small-only">
                <a href="?php echo App::config("url")?>/index">
                    <img src="?php echo App::config("url")?>public/logo.png" alt="Kreator Liga logo">
                </a>
            </div> -->
            
            <div class="large-12 medium-12 small-12 columns">
                <div id="center">
                    <h1><?php echo App::config("nazivApp") ?></h1>
                </div>
            </div>
        </div>

        <?php include_once "izbornik.phtml"?>

        <div class="callout" id="back" style="min-height: 400px;">
            <?php echo $content ?>
        </div>

        <div class="callout">
            &copy; Željko Livaja <?php echo date("Y") ?>
        </div>




    </div>

    <script src="<?php echo App::config("url") ?>public/js/vendor/jquery.js"></script>
    <script src="<?php echo App::config("url") ?>public/js/vendor/what-input.js"></script>
    <script src="<?php echo App::config("url") ?>public/js/vendor/foundation.js"></script>
    <script src="<?php echo App::config("url") ?>public/js/app.js"></script>
    <?php echo $js ?>

</body>

</html>