<form class="log-in-form" method="post" action="<?php echo App::config("url") ?>admin/login">

    <label>Korisničko ime
        <input type="text" name="username" value="Zelja">
    </label>
    <label>Lozinka
        <input type="password" name="password" value="t" placeholder="t">
    </label>

    <p><input type="submit" class="button expanded" value="Prijava" /></p>

</form>
<div id="poruka"> <?php echo $poruka ?> </div>