<form class="log-in-form" method="post" 
action="<?php echo App::config("url") ?>admin/login">

  <label>Username
    <input type="text" name="username" placeholder="Zelja"
    value="<?php echo Request::post("username") ?>">
  </label>
  <label>Password
    <input type="password" name="password" placeholder="t">
  </label>
 
  <p><input type="submit" class="button expanded" value="Log in" /></p>

</form>
<?php echo $poruka ?>


