<form class="log-in-form" method="post"
    action="<?php echo App::config("url") ?>liga/edit2/<?php echo Request::post("id") ?>">



    <label>Ime Lige
        <input type="text" name="nameOfLeague" value="<?php echo Request::post("nameOfLeague") ?>" />
    </label>

    <label>Opis Lige
        <input type="text" name="description" value="<?php echo Request::post("description") ?>" />
    </label>

    <label>
        <input type="hidden" name="gameType" value="<?php echo Request::post("gameType") ?>" />
    </label>

    <label>
        <input type="hidden" name="users" value="<?php echo Request::post("users") ?>" />
    </label>



    <div class="grid-x">
        <div class="large-6 columns" style="padding: 10px;">
            <a href="<?php echo App::config("url") ?>liga/index2" class="alert button expanded">
                Odustani
            </a>
        </div>
        <div class="large-6 columns" style="padding: 10px;">
            <input type="submit" class="success button expanded" value="Promjeni" />
        </div>
    </div>


</form>



<div class="grid-x">
    <a href="<?php echo App::config("url") ?>liga/index2" class="success button expanded">
    <i class="fas fa-arrow-left"></i>

Povratak
    </a>



    <table class="hover">
        <caption>
            <h4>Uređivanje klubova</h4>
        </caption>

        <thead>
            <tr>
                <th width="300">Klub</th>
                <th width="100">Obriši klub</th>

            </tr>
        </thead>
        <tbody>
        <?php $y=0; ?>
            <?php foreach($tablica as $podaci): ?>
            <tr>
                
                <td><?php echo $podaci->nameOfTeam?></td>
                <td style="text-align:left"><a style="color: red;"
                        href="<?php echo App::config("url") ?>table/delete2/<?php echo $podaci->id ?>">
                        <i class="fas fa-trash fa-2x"></i>
                        <a href="<?php echo App::config("url") ?>table/prepareedit2/<?php echo $podaci->id ?>">
                            <i class="fas fa-edit fa-2x"></i>
                        </a>

                    </a>
                </td>

            </tr>
            <?php $bodovi = $podaci->pointsPerWin ?>
            <?php $bodovix = $podaci->pointsPerDraw ?>
            <?php $league = $podaci->sifra ?>



            <?php endforeach; ?>

        </tbody>
    </table>


 
  