<div class="grid-container">
    <div class="grid-x align-center">

        <a href="<?php echo App::config("url") ?>liga/prepareadd2/<?php echo Session::getInstance()->getUser()->firstName?>"
        class="success button">
            Dodaj novu ligu
        </a>
    </div>

</div>
 
<div class="grid-x">

    <?php foreach($popis as $vrsta): ?>
    <?php if ($vrsta->description == 2) {
        ?>
    
    
    <div class="cell large-12 medium-12 small-12 text-center">
    
        <!-- <div class="success callout operateri"> -->
        <h5><strong><?php echo $vrsta->nameOfLeague?></strong> </h5>
        <p>     
        
        <?php $ime=$vrsta->nameOfLeague ?>
    <img src="<?php 
     
  
     $putanja = file_exists(App::config("path") . "public/img/" . $ime . ".png") 
     ?  App::config("url") . "public/img/" . $ime . ".png" 
     : App::config("url") . "public/img/nepoznato.png";

     echo $putanja ?>" alt="" />
  </p>
 
             <div> <?php echo $vrsta->gameName?> 
             </div>

            

        <a href="<?php echo App::config("url") ?>table/index2/<?php echo $vrsta->id?>" class="button">
            Tablica Lige
        </a>

        <a href="<?php echo App::config("url") ?>table/prepareadd2/<?php echo $vrsta->id?>" class="button">
            Dodaj novi klub
        </a>
        <?php if($vrsta->ukupno==0): ?>

        <a href="<?php echo App::config("url") ?>liga/delete2/<?php echo $vrsta->id?>" class="alert button">
            Obriši ligu
        </a>

<?php else: ?>
        <a href="#" class="alert button" title="prije brisanja lige obrišite sve njene klubove" disabled>
            Obriši ligu
        </a>

        <?php endif; ?>

        <a href="<?php echo App::config("url") ?>liga/prepareedit2/<?php echo $vrsta->id?>" class="button">
            Editiraj ligu
        </a>

        <a href="<?php echo App::config("url") ?>table/resetiraj2/<?php echo $vrsta->id?>" class="button" onclick="return confirm('Resetiranjem lige brišete sve rezultate i vraćate tablicu u početno stanje, jeste li sigurni?');" >
            Resetiraj ligu
        </a>

        <a href=" <?php echo App::config("url") ?>table/rezultati2/<?php echo $vrsta->id?>" class="button">
            Rezultati susreta
        </a>

        <a href=" <?php echo App::config("url") ?>igraci/top/<?php echo $vrsta->id?>" class="button">
            Top strijelci
        </a>
       




        <!-- </div> -->
        <hr>

    </div>
    <?php  } ?>
    <?php endforeach; ?>

</div>

 