 <table class="hover">

     <thead>
         <tr>
              <th width="500">Izaberite klub</th>
         </tr>
     </thead>
     <tbody>
         <?php foreach($popis as $podaci): ?>
         <tr>
 
             <td style="text-align:left">


                 <a href="<?php echo App::config("url") ?>igraci/lista/<?php echo $podaci->id?>" class="button expanded">
                 Klub <?php echo $podaci->nameOfTeam?>
         </a>

             </td>

         </tr>

         <?php endforeach; ?>

     </tbody>
 </table>