<table>
    <thead>
        <tr>
            <th>Administrator</th>
            <th>Ime</th>
            <th>Prezime</th>
            <th>Korisničko Ime</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($korisnici as $korisnik): ?>
        <tr>
            <td>

                <i class="fa<?php echo $korisnik->administrator ? "s" : "r" ?> fa-check-square"></i>

            </td>
            <td><?php echo $korisnik->firstName ?></td>
            <td><?php echo $korisnik->lastName ?></td>
            <td><?php echo $korisnik->username ?></td>

            <td>
                <a href="<?php echo App::config("url") ?>korisnik/prepareEdit/<?php echo $korisnik->id ?>">
               <i class="fas fa-edit fa-2x"></i>
                </a>
                <?php if($korisnik->ukupno==0): ?>
                    <a style="color: red;"
                     href="<?php echo App::config("url") ?>korisnik/delete/<?php echo $korisnik->id ?>">
                        <i class="fas fa-trash fa-2x"></i>
                    </a>
                <?php endif; ?>

            </td>
        </tr>
        <?php endforeach;?>
    </tbody>
    
</table>
<a href="<?php echo App::config("url") ?>korisnik/prepareAdd" class="success button expanded">
    Dodaj novog korisnika
</a>
