<form class="log-in-form" enctype="multipart/form-data" method="post"  method="post"
    action="<?php echo App::config("url") ?>liga/edit/<?php echo Request::post("id") ?>">
    <?php $ime=Request::post("nameOfLeague") ?>
    <img src="<?php 
     
  
     $putanja = file_exists(App::config("path") . "public/img/" . $ime . ".png") 
     ?  App::config("url") . "public/img/" . $ime . ".png" 
     : App::config("url") . "public/img/nepoznato.png";

     echo $putanja ?>" alt="" />



    <label>Ime Lige
        <input type="text" name="nameOfLeague" value="<?php echo Request::post("nameOfLeague") ?>" />
    </label>

    <label>Opis Lige
        <input type="text" name="description" value="<?php echo Request::post("description") ?>" />
    </label>

    <label>
        <input type="hidden" name="gameType" value="<?php echo Request::post("gameType") ?>" />
    </label>

    <label>
        <input type="hidden" name="users" value="<?php echo Request::post("users") ?>" />
    </label>

    
    <label>Editiraj sliku
        <input type="file" name="slika" />
    </label>



    <div class="grid-x">
        <div class="large-6 columns" style="padding: 10px;">
            <a href="<?php echo App::config("url") ?>liga/index" class="alert button expanded">
                Odustani
            </a>
        </div>
        <div class="large-6 columns" style="padding: 10px;">
            <input type="submit" class="success button expanded" value="Promjeni" />
        </div>
    </div>


</form>



<div class="grid-x">
    <a href="<?php echo App::config("url") ?>liga/index" class="success button expanded">
        <i class="fas fa-arrow-left"></i>

        Povratak
    </a>



    <table class="hover">
        <caption>
            <h4>Uređivanje klubova</h4>
        </caption>

        <thead>
            <tr>
                <th width="300">Klub</th>
                <th width="300">Grb</th>
                <th width="100">Obriši klub</th>

            </tr>
        </thead>
        <tbody>




            <?php $y=0; ?>
            <?php foreach($tablica as $podaci): ?>
            <tr>

                <td><?php echo $podaci->nameOfTeam?></td>
                <?php $ime=$podaci->nameOfTeam ?>
                <td> <?php $ime=Request::post("nameOfTeam"); ?>

                    <img src="<?php 
     
  
        $putanja = file_exists(App::config("path") . "public/img/" . $ime . ".png") 
        ?  App::config("url") . "public/img/" . $ime . ".png" 
        : App::config("url") . "public/img/nepoznato.png";

        echo $putanja ?>" alt="" />
                </td>



                <td style="text-align:left"><a style="color: red;"
                        href="<?php echo App::config("url") ?>table/delete/<?php echo $podaci->id ?>">
                        <i class="fas fa-trash fa-2x"></i>
                        <a href="<?php echo App::config("url") ?>table/prepareedit/<?php echo $podaci->id ?>">
                            <i class="fas fa-edit fa-2x"></i>
                        </a>

                    </a>
                </td>

            </tr>
            <?php $bodovi = $podaci->pointsPerWin ?>
            <?php $bodovix = $podaci->pointsPerDraw ?>
            <?php $league = $podaci->sifra ?>



            <?php endforeach; ?>

        </tbody>
    </table>