<form class="log-in-form" method="post"
    action="<?php echo App::config("url") ?>liga/edit/<?php echo Request::post("id") ?>">



    <label>Ime Lige
        <input type="text" name="nameOfLeague" value="<?php echo Request::post("nameOfLeague") ?>" />
    </label>

    <label>Opis Lige
        <input type="text" name="description" value="<?php echo Request::post("description") ?>" />
    </label>

    <label>
        <input type="hidden" name="gameType" value="<?php echo Request::post("gameType") ?>" />
    </label>
    
    <label>
        <input type="hidden" name="users" value="<?php echo Request::post("users") ?>" />
    </label>



    <div class="grid-x">
        <div class="large-6 columns" style="padding: 10px;">
            <a href="<?php echo App::config("url") ?>lige/index" class="alert button expanded">
                Odustani
            </a>
        </div>
        <div class="large-6 columns" style="padding: 10px;">
            <input type="submit" class="success button expanded" value="Promjeni" />
        </div>
    </div>


</form>