<div class="grid-x">

    <?php foreach($popis as $vrsta): ?>
    
    <div class="cell large-12 medium-12 small-12 text-center">
    
        <!-- <div class="success callout operateri"> -->
        <h5><strong><?php echo $vrsta->nameOfLeague?></strong> </h5>
 
             <div> <?php echo $vrsta->gameName?> 
             </div>

            

        <a href="<?php echo App::config("url") ?>table/index/<?php echo $vrsta->id?>" class="button">
            Tablica Lige
        </a>

        <a href="<?php echo App::config("url") ?>table/prepareadd/<?php echo $vrsta->id?>" class="button">
            Dodaj novi klub
        </a>
        <?php if($vrsta->ukupno==0): ?>

        <a href="<?php echo App::config("url") ?>liga/delete/<?php echo $vrsta->id?>" class="alert button">
            Obriši ligu
        </a>

<?php else: ?>
        <a href="#" class="alert button" title="prije brisanja lige obrišite sve njene klubove" disabled>
            Obriši ligu
        </a>

        <?php endif; ?>

        <a href="<?php echo App::config("url") ?>liga/prepareedit/<?php echo $vrsta->id?>" class="button">
            Editiraj ligu
        </a>

        <a href="<?php echo App::config("url") ?>table/resetiraj/<?php echo $vrsta->id?>" class="button">
            Resetiraj ligu
        </a>

        <a href=" <?php echo App::config("url") ?>table/rezultati/<?php echo $vrsta->id?>" class="button">
            Rezultati susreta
        </a>

        <a href=" <?php echo App::config("url") ?>igraci/top/<?php echo $vrsta->id?>" class="button">
            Top strijelci
        </a>
       




        <!-- </div> -->
        <hr>

    </div>
    <?php endforeach; ?>

</div>
<div class="grid-container">
    <div class="grid-x align-center">

        <a href="<?php echo App::config("url") ?>liga/prepareadd/<?php echo Session::getInstance()->getUser()->firstName?>"
        class="success button">
            Dodaj novu ligu
        </a>
    </div>

</div>
 