<div class="grid-x">

    <?php foreach($popis as $vrsta): ?>
    <div class="cell large-4 medium-6 small-12">
        <!-- <div class="success callout operateri"> -->
        <h5><strong> Naziv lige: <?php echo $vrsta->nameOfLeague?>
                <br />
               Opis: <?php echo $vrsta->description?>
                <br />

               Vrsta sporta: <?php echo $vrsta->gameName?>

             </strong></h5>

        <a href="<?php echo App::config("url") ?>table/index/<?php echo $vrsta->id?>" class="button">
            Tablica Lige
        </a>

        <a href="<?php echo App::config("url") ?>table/prepareadd/<?php echo $vrsta->id?>" class="success button">
            Dodaj novi klub
        </a>
        <?php if($vrsta->ukupno==0): ?>

        <a href="<?php echo App::config("url") ?>liga/delete/<?php echo $vrsta->id?>" class="alert button">
            Obriši ligu
        </a>

<?php else: ?>
        <a href="#" class="alert button" title="prije brisanja lige obrišite sve njene klubove" disabled>
            Obriši ligu
        </a>

        <?php endif; ?>

        <a href="<?php echo App::config("url") ?>liga/prepareedit/<?php echo $vrsta->id?>" class="button warning">
            Editiraj ligu
        </a>

        <a href=" <?php echo App::config("url") ?>table/rezultati/<?php echo $vrsta->id?>" class="button warning">
            Rezultati susreta
        </a>
       



        <!-- </div> -->
    </div>

    <?php endforeach; ?>

</div>
<div class="grid-container">
    <div class="grid-x align-center">

        <a href="<?php echo App::config("url") ?>liga/prepareadd/<?php echo Session::getInstance()->getUser()->firstName?>"
        class="success button">
            Dodaj novu ligu
        </a>
    </div>

</div>
 