<link href="https://unpkg.com/tabulator-tables@4.2.4/dist/css/tabulator.min.css" rel="stylesheet">
<script type="text/javascript" src="https://unpkg.com/tabulator-tables@4.2.4/dist/js/tabulator.min.js"></script>


<div class="grid-x">
<div class="cell"> 

    <a href="<?php echo App::config("url") ?>liga/index2" class="success button expanded">
    <i class="fas fa-arrow-left"></i>

Povratak
    </a>

    <?php foreach($tablica as $podaci){
                 
                 $ime = $podaci->nameOfLeague;
                  }
                   ?>
 
    </div>

    <div class="cell large-12 text-center">
  <img src="<?php 
 
 
 $putanja = file_exists(App::config("path") . "public/img/" . $ime . ".png") 
 ?  App::config("url") . "public/img/" . $ime . ".png" 
 : App::config("url") . "public/img/nepoznato.png";
 
 echo $putanja ?>" alt="" width="200" height="200" />
 </div>

 <p>
    <div class="cell large-12"> <p class="text-center"> <b>#LJESTVICA</b> </p>
     </div>


    <table class="hover" id="example-table">

    <?php foreach($tablica as $podaci){
                 
                 $ime = $podaci->nameOfLeague;
                  }
                   ?>
 
 
                   
 
        <caption>
            <h4>Ljestvica</h4>
        </caption>

        <thead>
            <tr>
                <th width="10">#</th>
                <th width="150">Klub</th>
                <th width="80">Uk</th>
                <th width="80">Bod</th>
                <th width="80" class="hide-for-small-only">Pob</th>
                <th width="80" class="hide-for-small-only">Por</th>
                <th width="80" class="hide-for-small-only">Ner</th>
                <th width="80" class="hide-for-small-only">G+</th>
                <th width="80" class="hide-for-small-only">G-</th>
 
            </tr>
        </thead>
        <tbody>
        <?php $y=0; ?>
            <?php foreach($tablica as $podaci): ?>
            <tr>
                
                <td><?php echo $y+=1; ?></td>
                <td><?php echo $podaci->nameOfTeam?></td>
                <td style="text-align:left"><?php echo $podaci->totalGamesPlayed?></td>
                <td style="text-align:left"><?php echo $podaci->totalPoints?></td>
                <td style="text-align:left" class="hide-for-small-only"><?php echo $podaci->totalWins?></td>
                <td style="text-align:left" class="hide-for-small-only"><?php echo $podaci->totalLosses?></td>
                <td style="text-align:left" class="hide-for-small-only"><?php echo $podaci->totalDraws?></td>
                <td style="text-align:left" class="hide-for-small-only"><?php echo $podaci->totalGoalsScored?></td>
                <td style="text-align:left" class="hide-for-small-only"><?php echo $podaci->totalGoalsConceded?></td>
 
            </tr>
            <?php $bodovi = $podaci->pointsPerWin ?>
            <?php $bodovix = $podaci->pointsPerDraw ?>
            <?php $league = $podaci->sifra ?>



            <?php endforeach; ?>

        </tbody>
    </table>


    <script>var table = new Tabulator("#example-table", {
            responsiveLayout:"hide",
            columns:[
    {title:"#", responsive:0}, //never hide this column
    {title:"Klub", responsive:0 },
    {title:"Uk", responsive:0 },
    {title:"Bod", responsive:0 },
     ],


    });
</script>

 
    <div class="cell large-12" id="raspored"> <p class="text-center"> <b>Raspored odigravanja utakmica:</b> </p>
        <hr>
    </div>
    <br />
    <?php foreach($schedule as $round => $games):?>
    <div class="cell large-3 small-6">


        <b> <?php echo "Kolo: ".($round+1)."<BR>"; ?> </b>

        <?php foreach($games AS $play){ ?>
        <?php  if($play["Home"]=="slobodan" or $play["Away"]=="slobodan"){
           
           if($play["Home"]!=="slobodan"){
               
               echo  $play["Home"]. " preskace ovo kolo"."<BR>";
            

           }

           if($play["Away"]!=="slobodan"){
          
            echo  $play["Away"]. " preskace ovo kolo"."<BR>";
                  }

           
           continue;        
           } ?>
        <?php
         
      echo $play["Home"]." - ".$play["Away"]."<BR>"; 
    

    }?>
        <br>
    </div>


    <?php endforeach; ?>
    <?php $f=$round+2; ?>


  
    <br />
    <?php foreach($schedule as $round => $games):?>
    <div class="cell large-3 small-6">

        <b> <?php echo "Kolo: ".($round+$f)."<BR>"; ?> </b>

        <?php foreach($games AS $play){ ?>
        <?php  if($play["Home"]=="slobodan" or $play["Away"]=="slobodan"){
           
           if($play["Home"]!=="slobodan"){
               
               echo  $play["Home"]. " preskace ovo kolo"."<BR>";
            

           }

           if($play["Away"]!=="slobodan"){
          
            echo  $play["Away"]. " preskace ovo kolo"."<BR>";
                  }

           
           continue;        
           } ?>
        <?php
         
      echo $play["Away"]. " - " . $play["Home"] . "<BR>"; 
    

    }?>
        <br>
    </div>


    <?php endforeach; ?>




</div>

<?php include_once "updateresult.phtml" ?>
<?php include_once "updateresult2.phtml" ?>



</div>

</div>


 