<?php foreach($podaci1 as $podaci): ?>

<form class="log-in-form" method="post"
    action="<?php echo App::config("url") ?>vrsta/edit">

    <label>Naziv sporta
        <input type="text" name="gameName" value="<?php echo $podaci->gameName ?>"/>
    </label>

    
    <label>Bodovi u slučaju pobjede
        <input type="number" name="pointsPerWin" value="<?php echo $podaci->pointsPerWin ?>"/>
    </label>

    <label>Bodovi u slučaju nerješenog rezultata
        <input type="number" name="pointsPerDraw" value="<?php echo $podaci->pointsPerDraw ?>"/>
    </label>

    <label>Bodovi u slučaju poraza
        <input type="number" name="pointsPerLoss" value="<?php echo $podaci->pointsPerLoss ?>"/>
    </label>

    <label>opis natjecanja
        <input type="text" name="description" value="<?php echo $podaci->description ?>"/>
    </label>

   
    <label> 
        <input type="hidden" name="id" value="<?php echo $podaci->id ?>" />
    </label>

 

    <div class="grid-x">
        <div class="large-6 columns" style="padding: 10px;">
            <a href="<?php echo App::config("url") ?>vrsta/index" class="alert button expanded">
                Odustani
            </a>
            

        </div>
        <div class="large-6 columns" style="padding: 10px;">
            <input type="submit" class="success button expanded" value="Dodaj Igrača" />
        </div>
    </div>

</form>
<?php endforeach; ?>

<?php echo $poruka ?>


 