<form class="log-in-form" method="post" enctype="multipart/form-data"
    action="<?php echo App::config("url") ?>table/edit/<?php echo Request::post("id") ?>">
    <?php $ime=Request::post("nameOfTeam"); ?>

    <img src="<?php 
            /*
            $putanja=App::config("path") . "public/img/polaznici/nepoznato.png";
            
            if(file_exists(App::config("url") . "public/img/polaznici/" . $p->sifra . ".png")){
                $putanja = App::config("url") . "public/img/polaznici/" . $p->sifra . ".png";
            }
            */
      
            $putanja = file_exists(App::config("path") . "public/img/" . $ime . ".png") 
            ?  App::config("url") . "public/img/" . $ime . ".png" 
            : App::config("url") . "public/img/nepoznato.png";

            echo $putanja ?>" alt="" />


    <label>Ime Kluba
        <input type="text" name="nameOfTeam" value="<?php echo Request::post("nameOfTeam") ?>" />
    </label>

    <label>Osvojeni bodovi
        <input type="number" name="totalPoints" value="<?php echo Request::post("totalPoints") ?>" />
    </label>

    <label>Zabijeni golovi
        <input type="number" name="totalGoalsScored" value="<?php echo Request::post("totalGoalsScored") ?>" />
    </label>

    <label>Primljeni golovi
        <input type="number" name="totalGoalsConceded" value="<?php echo Request::post("totalGoalsConceded") ?>" />
    </label>

    <label>
        <input type="hidden" name="id" value="<?php echo Request::post("id") ?>" />
    </label>

    <label>
        <input type="hidden" name="league" value="<?php echo Request::post("league") ?>" />
    </label>

    <label>Editiraj sliku
        <input type="file" name="slika" />
    </label>




    <div class="grid-x">
        <div class="large-6 columns" style="padding: 10px;">
            <a href="<?php echo App::config("url") ?>liga/index" class="alert button expanded">
                Odustani
            </a>
        </div>
        <div class="large-6 columns" style="padding: 10px;">
            <input type="submit" class="success button expanded" value="Promjeni" />
        </div>
    </div>


</form>

<?php echo $putanja ?>
<?php echo $ime ?>