<form class="log-in-form" method="post"
    action="<?php echo App::config("url") ?>table/edit/<?php echo Request::post("id") ?>">



    <label>Ime Kluba
        <input type="text" name="nameOfTeam" value="<?php echo Request::post("nameOfTeam") ?>" />
    </label>

    <label>Osvojeni bodovi
        <input type="text" name="totalPoints" value="<?php echo Request::post("totalPoints") ?>" />
    </label>

    <label>Zabijeni golovi
        <input type="text" name="totalGoalsScored" value="<?php echo Request::post("totalGoalsScored") ?>" />
    </label>
    
    <label>Primljeni golovi
        <input type="text" name="totalGoalsConceded" value="<?php echo Request::post("totalGoalsConceded") ?>" />
    </label>

    <label>
        <input type="hidden" name="id" value="<?php echo Request::post("id") ?>" />
    </label>

    <label>
        <input type="hidden" name="league" value="<?php echo Request::post("league") ?>" />
    </label>



    <div class="grid-x">
        <div class="large-6 columns" style="padding: 10px;">
            <a href="<?php echo App::config("url") ?>liga/index" class="alert button expanded">
                Odustani
            </a>
        </div>
        <div class="large-6 columns" style="padding: 10px;">
            <input type="submit" class="success button expanded" value="Promjeni" />
        </div>
    </div>


</form>