<div class="grid-x">
    <a href="<?php echo App::config("url") ?>liga/index" class="success button">
        Povratak
    </a>



    <table class="hover">
        <caption>
            <h4>Ljestvica</h4>
        </caption>

        <thead>
            <tr>
                <th width="200">Klub</th>
                <th width="100">Utakmice</th>
                <th width="100">Osvojeni Bodovi</th>
                <th width="100" class="hide-for-small-only">Pobjede</th>
                <th width="100" class="hide-for-small-only">Porazi</th>
                <th width="100" class="hide-for-small-only">Nerješene</th>
                <th width="100" class="hide-for-small-only">Zabijeni golovi</th>
                <th width="100" class="hide-for-small-only">Primljeni golovi</th>
                <th width="100">Obriši klub</th>

            </tr>
        </thead>
        <tbody>
            <?php foreach($tablica as $podaci): ?>
            <tr>
                <td><?php echo $podaci->nameOfTeam?></td>
                <td style="text-align:left"><?php echo $podaci->totalGamesPlayed?></td>
                <td style="text-align:left"><?php echo $podaci->totalPoints?></td>
                <td style="text-align:left" class="hide-for-small-only"><?php echo $podaci->totalWins?></td>
                <td style="text-align:left" class="hide-for-small-only"><?php echo $podaci->totalLosses?></td>
                <td style="text-align:left" class="hide-for-small-only"><?php echo $podaci->totalDraws?></td>
                <td style="text-align:left" class="hide-for-small-only"><?php echo $podaci->totalGoalsScored?></td>
                <td style="text-align:left" class="hide-for-small-only"><?php echo $podaci->totalGoalsConceded?></td>
                <td style="text-align:left"><a style="color: red;"
                        href="<?php echo App::config("url") ?>table/delete/<?php echo $podaci->id ?>">
                        <i class="fas fa-trash fa-2x"></i>
                        <a href="<?php echo App::config("url") ?>table/prepareedit/<?php echo $podaci->id ?>">
                            <i class="fas fa-edit fa-2x"></i>
                        </a>

                    </a>
                </td>

            </tr>
            <?php $bodovi = $podaci->pointsPerWin ?>
            <?php $bodovix = $podaci->pointsPerDraw ?>
            <?php $league = $podaci->sifra ?>



            <?php endforeach; ?>

        </tbody>
    </table>


 
    <div class="cell large-12"> <b>Raspored odigravanja utakmica, prvi krug:</b>
        <hr>
    </div>
    <br />
    <?php foreach($schedule as $round => $games):?>
    <div class="cell large-3 small-6">


        <b> <?php echo "Kolo: ".($round+1)."<BR>"; ?> </b>

        <?php foreach($games AS $play){ ?>
        <?php  if($play["Home"]=="slobodan" or $play["Away"]=="slobodan"){
           
           if($play["Home"]!=="slobodan"){
               
               echo  $play["Home"]. " preskace ovo kolo"."<BR>";
            

           }

           if($play["Away"]!=="slobodan"){
          
            echo  $play["Away"]. " preskace ovo kolo"."<BR>";
                  }

           
           continue;        
           } ?>
        <?php
         
      echo $play["Home"]." - ".$play["Away"]."<BR>"; 
    

    }?>
        <br>
    </div>


    <?php endforeach; ?>


    <div class="cell large-12"> <b>Raspored odigravanja utakmica, drugi krug:</b>
        <hr>
    </div>
    <br />
    <?php foreach($schedule as $round => $games):?>
    <div class="cell large-3 small-6">


        <b> <?php echo "Kolo: ".($round+1)."<BR>"; ?> </b>

        <?php foreach($games AS $play){ ?>
        <?php  if($play["Home"]=="slobodan" or $play["Away"]=="slobodan"){
           
           if($play["Home"]!=="slobodan"){
               
               echo  $play["Home"]. " preskace ovo kolo"."<BR>";
            

           }

           if($play["Away"]!=="slobodan"){
          
            echo  $play["Away"]. " preskace ovo kolo"."<BR>";
                  }

           
           continue;        
           } ?>
        <?php
         
      echo $play["Away"]. " - " . $play["Home"] . "<BR>"; 
    

    }?>
        <br>
    </div>


    <?php endforeach; ?>




</div>

<?php include_once "updateresult.phtml" ?>
<?php include_once "updateresult2.phtml" ?>



</div>

</div>


 