<hr>

<!-- <b>Unos rezultata drugog kruga: (opcionalno) </b> -->
<hr>
<?php 
 $a1=0; 
 $b1=0; 
 $c1=0; 
 $d1=0; ?>
<?php foreach($schedule as $round => $games): ?>
<br />


<b> <?php echo "Kolo: ".($round+$f)."<br/>"?> </b>



<?php foreach($games AS $play): ?>
<?php  if($play["Home"]==="slobodan" or $play["Away"]==="slobodan"){
    continue;
}  ?>

<button title="kliknite za unos" onclick="myyFunction<?php echo $a1+=1;?>()"><?php echo $play["Away"] . " vs " . $play["Home"] ; ?></button>
<br />
<div id="myyDIV<?php echo $b1+=1;?>" style="display:none;">

    <script>
    function myyFunction<?php echo $c1+=1; ?>() {
        var x = document.getElementById("myyDIV<?php echo $d1+=1; ?>");
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
        }
    }
    </script>


    <form class="log-in-form" method="post" action="<?php echo App::config("url") ?>table/insert/">

    


        <label> Ime Kluba
            <input type="text" name="awayTeam" value="<?php echo $play["Away"] ?>" readonly />
        </label>


        <label> <b> Postignuti Golovi kluba <?php echo $play["Away"] ?> </b>
            <input type="number" name="awayTeamGoals" />
        </label>

        <label> Ime Kluba
            <input type="text" name="homeTeam" value="<?php echo $play["Home"] ?>" readonly />
        </label>

        <label><b> Postignuti Golovi kluba <?php echo $play["Home"] ?> </b>
            <input type="number" name="homeTeamGoals" />
        </label>


        <label>
            <input type="hidden" name="totalPointsWin" value="<?php echo $bodovi ?>" readonly />
        </label>

        <label>
            <input type="hidden" name="description" value="2" readonly />
        </label>


        <label>
            <input type="hidden" name="games" value=1 readonly />
        </label>

        <label>
            <input type="hidden" name="totalPointsDraw" value="<?php echo $bodovix ?>" readonly />
        </label>

        <label>
            <input type="hidden" name="league" value="<?php echo $league ?>" readonly />
        </label>




        <div class="grid-x">
            <div style="padding: 10px;">
                <a href="#" class="alert button">
                    Odustani
                </a>


            </div>
            <div style="padding: 10px;">
                <input type="submit" class="success button" value="Dodaj utakmicu" />
            </div>


        </div>
        <br />

    </form>
</div>

<?php  endforeach; ?>
<?php endforeach; ?>