<br/>
<b>Unos rezultata prvog kruga: </b>
<hr>
<?php 
 $a=0; 
 $b=0; 
 $c=0; 
 $d=0; ?>
<?php foreach($schedule as $round => $games): ?>
<br />


<b> <?php echo "Kolo: ".($round+1)."<br/>"?> </b>


<?php $e=0; ?>


<?php foreach($games AS $play): ?>
<?php  if($play["Home"]==="slobodan" or $play["Away"]==="slobodan"){
    continue;
}  ?>

<button title="kliknite za unos" onclick="myFunction<?php echo $a+=1;?>()"><?php echo $play["Home"] . " vs " . $play["Away"] ; ?></button>
<br />
<div id="myDIV<?php echo $b+=1;?>" style="display:none;">

    <script>
    function myFunction<?php echo $c+=1; ?>() {
        var x = document.getElementById("myDIV<?php echo $d+=1; ?>");
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
        }
    }
    </script>


    <form class="log-in-form" method="post" action="<?php echo App::config("url") ?>table/insert/">

        <label> Ime Kluba
            <input type="text" name="homeTeam" value="<?php echo $play["Home"] ?>" readonly />
        </label>

        <label><b> Postignuti Golovi kluba <?php echo $play["Home"] ?> </b>
            <input type="number" name="homeTeamGoals" />
        </label>


        <label> Ime Kluba
            <input type="text" name="awayTeam" value="<?php echo $play["Away"] ?>" readonly />
        </label>


        <label> <b> Postignuti Golovi kluba <?php echo $play["Away"] ?> </b>
            <input type="number" name="awayTeamGoals" />
        </label>


        <label>
            <input type="hidden" name="totalPointsWin" value="<?php echo $bodovi ?>" readonly />
        </label>

        <label>
            <input type="hidden" name="description" value="1" readonly />
        </label>


        <label>
            <input type="hidden" name="games" value=1 readonly />
        </label>

        <label>
            <input type="hidden" name="totalPointsDraw" value="<?php echo $bodovix ?>" readonly />
        </label>

        <label>
            <input type="hidden" name="league" value="<?php echo $league ?>" readonly />
        </label>




        <div class="grid-x">
            <div style="padding: 10px;">
                <a href="#" class="alert button">
                    Odustani
                </a>


            </div>
            <div style="padding: 10px;">
                <input type="submit" class="success button" value="Dodaj utakmicu" />
            </div>


        </div>
        <br />

    </form>
</div>

<?php  endforeach; ?>
<?php endforeach; ?>