<?php foreach($schedule as $round => $games): ?>

<?php echo "Kolo: ".($round+1)."<br/>"."<hr/>"; ?>
<?php foreach($games AS $play): ?>

<form class="log-in-form" method="post" action="<?php echo App::config("url") ?>table/insert/">


 
    <?php  if($play["Home"]==="slobodan" or $play["Away"]==="slobodan"){    
    continue;
} ?>
    <label> Ime Kluba
        <input type="text" name="homeTeam" value="<?php echo $play["Home"] ?>" readonly />
    </label>

    <label><b> Postignuti Golovi kluba <?php echo $play["Home"] ?> </b>
        <input type="number" name="homeTeamGoals" />
    </label>


    <label> Ime Kluba
        <input type="text" name="awayTeam" value="<?php echo $play["Away"] ?>" readonly />
    </label>


    <label> <b> Postignuti Golovi kluba <?php echo $play["Away"] ?> </b>
        <input type="number" name="awayTeamGoals" />
    </label>


    <label>
        <input type="hidden" name="totalPointsWin" value="<?php echo $bodovi ?>" readonly />
    </label>

    <label>
        <input type="hidden" name="totalPointsDraw" value="<?php echo $bodovix ?>" readonly />
    </label>

    <label>
        <input type="hidden" name="league" value="<?php echo $league ?>" readonly />
    </label>







    <div class="grid-x">
        <div style="padding: 10px;">
            <a href="#" class="alert button">
                Odustani
            </a>


        </div>
        <div style="padding: 10px;">
            <input type="submit" class="success button" value="Dodaj utakmicu" />
        </div>


    </div>
    <br />

</form>
<?php  endforeach; ?>


    <?php endforeach; ?>